final version of json.py
TypeError: string indices must be integers. This error was the big hurdle on this assignment. when running my for loop I did not have ['comments'] and this is what caused this error for me. I was not parsing through the json correctly until I added the comments bit.